DROP TABLE IF EXISTS comments,bookings,items,requests,users;

CREATE TABLE IF NOT EXISTS users
(

    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name  VARCHAR(100)                            NOT NULL,
    email VARCHAR(60)                             NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS requests
(

    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    description  VARCHAR(512)                            NOT NULL,
    requestor_id BIGINT                                  NOT NULL references users on delete cascade,
    created      date                                    not null
);

CREATE TABLE IF NOT EXISTS items
(

    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name            VARCHAR(255)                            NOT NULL,
    description     VARCHAR(512)                            NOT NULL,
    available       BOOLEAN                                 NOT NULL,
    owner_id        BIGINT                                  NOT NULL REFERENCES users on delete cascade,
    request_id      BIGINT REFERENCES requests,
    last_booking_id BIGINT,
    next_booking_id BIGINT
);

CREATE TABLE IF NOT EXISTS bookings
(

    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    item_id    BIGINT                                  NOT NULL REFERENCES items on delete cascade,
    booker_id  BIGINT                                  NOT NULL REFERENCES users on delete cascade,
    status     varchar(255)                            not null
);

CREATE TABLE IF NOT EXISTS comments
(

    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    text      VARCHAR(512)                            NOT NULL,
    item_id   BIGINT                                  NOT NULL REFERENCES items on delete cascade,
    author_id BIGINT                                  NOT NULL REFERENCES users on delete cascade,
    created   TIMESTAMP WITHOUT TIME ZONE             not null
);

